export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const FETCH_ALL_JOBS_START = 'FETCH_ALL_JOBS_START';
export const FETCH_ALL_JOBS_SUCCESS = 'FETCH_ALL_JOBS_SUCCESS';
export const FETCH_ALL_JOBS_FAILED = 'FETCH_ALL_JOBS_FAILED';

export const FETCH_JOBS_BY_KEYWORD_START = 'FETCH_JOBS_BY_KEYWORD_START';
export const FETCH_JOBS_BY_KEYWORD_SUCCESS = 'FETCH_JOBS_BY_KEYWORD_SUCCESS';
export const FETCH_JOBS_BY_KEYWORD_FAILED = 'FETCH_JOBS_BY_KEYWORD_FAILED';
